[package]
name = "heck_playground"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.4.1"
leptos = { version = "0.5.1", features = ["csr"] }
